cleaned up the code and fixed indentations
danthe1st/JDoc4droid pull request #3
Opened 2022-02-08 14:01 UTC by sahilasopa

Fixed indentations and did some minor refactoring to code

2022-02-08 14:44 UTC, danthe1st requested changes

2022-02-08 14:44 UTC, danthe1st commented on app/src/main/java/io/github/danthe1st/jdoc4droid/model/textholder/HtmlStringHolder.java
> -    @NonNull
If you remove `@NonNull` in here, can you please also remove `@NoArgsConstructor` and `@RequiredArgsConstructor`?

2022-02-08 14:52 UTC, danthe1st requested changes
It seems like you forgot to reformat `io.github.danthe1st.jdoc4droid.activities.list` and `io.github.danthe1st.jdoc4droid.activities.list.javadocs`.

2022-02-08 16:03 UTC, sahilasopa commented
> It seems like you forgot to reformat `io.github.danthe1st.jdoc4droid.activities.list` and `io.github.danthe1st.jdoc4droid.activities.list.javadocs`.

alright done

2022-02-08 16:08 UTC, danthe1st requested changes

2022-02-08 16:08 UTC, danthe1st commented on app/src/main/java/io/github/danthe1st/jdoc4droid/activities/list/javadocs/ListJavadocsActivity.java
> +    @WorkerThread
Again, please don't move methods.

2022-02-09 16:07 UTC, danthe1st approved these changes

2022-02-09 16:07 UTC, merged